
matrix:
  include:
    - language: java
      dist: bionic

      addons:
        sonarcloud:
          organization: "win32service"

      script:
        - sonar-scanner -Dsonar.projectKey=win32service_service-library -Dsonar.organization=win32service -Dsonar.sources=./lib -Dsonar.host.url=https://sonarcloud.io -Dsonar.test.inclusions=tests/**

    - language: php
      dist: bionic
      php:
        - 7.4
      before_script:
        - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
      script:
        - composer install
        - php vendor/bin/psalm.phar
        - php php-cs-fixer fix --dry-run --diff
