name: CI

on:
  push:
    branches: ['1.x']
  pull_request:
    branches: [ "1.x" ]

permissions:
  contents: read

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
      - uses: actions/checkout@v7

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-interaction --no-progress --prefer-dist

      - run: vendor/bin/phpunit

  static-analysis:
    name: PHPStan and PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: php-cs-fixer

      - run: composer install --no-interaction --no-progress --prefer-dist

      - run: php-cs-fixer fix --dry-run --diff

      - run: vendor/bin/phpstan analyse --no-progress
